apiVersion: v1
kind: Service
metadata:
  name: kademlia-service
  namespace: default # Kademlia Pod가 배포될 네임스페이스와 동일
spec:
  selector:
    app: kademlia-node # Kademlia Deployment의 Pod를 선택합니다.
  ports:
    - protocol: UDP # Kademlia는 UDP 통신을 사용합니다.
      port: 8468    # Service가 리스닝할 포트
      targetPort: 8468 # Pod의 컨테이너가 리스닝하는 포트
  type: ClusterIP # Kademlia 노드 간 통신은 클러스터 내부에서 이루어지므로 ClusterIP가 적합합니다.
                  # 외부에서 직접 Kademlia 노드로 접근할 필요는 거의 없습니다.