# flask-api-server/kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-api-server-service
spec:
  selector:
    app: flask-api-server
  ports:
    - protocol: TCP
      port: 80 # 서비스 포트
      targetPort: 5000 # 컨테이너 포트
  type: LoadBalancer # 또는 NodePort, ClusterIP (필요에 따라 선택)
                     # LoadBalancer는 클라우드 환경에서 외부 IP를 자동으로 할당
                     # NodePort는 클러스터 노드의 특정 포트를 통해 접근 가능 (개발/테스트용)
                     # ClusterIP는 클러스터 내부에서만 접근 가능 (Ingress와 함께 사용)